version: 2
jobs:
    checkout-and-cache-dependencies:
        working_directory: ~/testing-helpers
        docker:
            - image: circleci/node:12.13.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn
            - save_cache:
                  key: dependency-cache-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
    release:
        working_directory: ~/testing-helpers
        docker:
            - image: circleci/node:12.13.0
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - dependency-cache-{{ checksum "yarn.lock" }}
            - run: yarn
            - run: yarn build
            - run: yarn semantic-release

workflows:
    version: 2
    checkout-release:
        jobs:
            - checkout-and-cache-dependencies
            - release:
                  requires:
                      - checkout-and-cache-dependencies
                  filters:
                      branches:
                          only:
                              - master
