name: build
on: push

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN_SEMANTIC_RELEASE }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: yarn

            - name: Configure Git
              run: git config --global --add url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"

            - name: Configure npmrc
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc

            - name: Install dependencies
              run: yarn --frozen-lockfile --prefer-offline

            - name: Lint commit message
              run: yarn commitlint --from=HEAD~1

            - name: Check ESLint
              run: yarn lint

            - name: Build package
              run: yarn build

            - name: Semantic Release
              run: yarn semantic-release
